# Prelude Test

This test has been created to ensure a candidate has adequete knowledge in Linear Algebra, Calculus and Probability. Some concepts may be new to a candidate - but we encourage the use of Googling and looking at external resources in order to gain a stronger understanding and solve the problem. 

The Linear Algebra section of this test is heavily inspired from: https://www.researchgate.net/publication/246546380_Singular_Value_Decomposition_Tutorial. Feel free to use it as a reference if you need description/clarification of a concept.

Provide comments where you think it would be useful

## Create a vector object

Add methods to this object which: 
1. Calculate the length/norm of a vector
2. Scalar multiplies a vector
3. Returns the unit vector of the vector

Until permitted, the ONLY Numpy method you should use is np.array(). However, the use of the inbuilt math library is fully permitted

In [2]:
import numpy as np
import math

In [19]:
class Vector():
    def __init__():
        
    def scalar_multiply():
    
    def length():
    
    def unit_vector():

In [20]:
v_ = np.array([2,4,1,2])
vector = Vector(v_)
print(vector.scalar_multiply(1.5))
print(vector.length())
print(vector.unit_vector())

[3.  6.  1.5 3. ]
5.0
[0.4 0.8 0.2 0.4]


### A static method...
is a method which is run against the class itself, rather than an instance of the class. [More information can be found here](https://www.journaldev.com/18722/python-static-method).

Copy the vector class you defined above and add static methods which facilitate:

1. Adding two vectors
2. Calculating the inner product of two vectors
3. Checking whether two vectors are orthogonal to each other (returns a boolean - true if orthogonal, false otherwise)


In [184]:
class Vector():
    def __init__():
    
    def scalar_multiply():
    
    
    def length():
    

    def unit_vector():
        
    
    @staticmethod
    def add():
        # Do NOT just directly add the vectors together using the "+" operator
     
    
    @staticmethod
    def inner():


    @staticmethod
    def orthogonal():


In [185]:
vec1 = np.array([2,1,-2,4])
vec2 = np.array([3,-6,4,2])

print(Vector.add(vec1, vec2))
print(Vector.inner(vec1, vec2))
print(Vector.orthogonal(vec1, vec2))

[ 5 -5  2  6]
0
True


## Create a function which multiplies two matricies together
Use nested for loops to implement the algorithm. Comment what the algorithm/each for loop is doing in as much detail as possible

In [34]:
def matmul(mat1, mat2):
    mat1_rows = mat1.shape[0]
    mat1_cols = mat1.shape[1]
    mat2_rows = mat2.shape[0]
    mat2_cols = mat2.shape[1]
    
    assert mat1_cols == mat2_rows, "Incompatible shapes between the two matrices. Mat1 cols should be the same as Mat2 rows"
    print("New Matrix shape is going to be: [{} x {}]".format(mat1_rows, mat2_cols))
    
    result = np.zeros((mat1_rows, mat2_cols))
    
    ## Add matrix multiplication code here
    
                
    return result

In [35]:
X = np.asarray([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])
# 3x4 matrix
Y = np.asarray([[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]])

print(matmul(X, Y))

New Matrix shape is going to be: [3 x 4]
[[114. 160.  60.  27.]
 [ 74.  97.  73.  14.]
 [119. 157. 112.  23.]]


## Determinants, Eigenvalues and Eigenvectors
### By hand...
Calculate the determinant of the following two matricies:
$$
\begin{bmatrix}
6 & 2 \\
3 & 2
\end{bmatrix} \\
\begin{bmatrix}
2 & -3 & 4 \\
1 & 1 & -8 \\
3 & 2 & 5
\end{bmatrix}
$$

Calculate the eigenvalues and eigenvectors of the matrix:
$$
\begin{bmatrix}
3 & -2 \\
-6 & 7
\end{bmatrix}
$$

Please show your work

## Singular Value Decomposition

In this part of the assessment, we will run you through an implementation of an algorithm known as Singular Value Decomposition (SVD). If this is your first introduction to this algorithm, we highly recommend [reading the tutorial](https://www.researchgate.net/publication/246546380_Singular_Value_Decomposition_Tutorial) linked at the top of the document.

SVD is given by the formula:
$$
\mathbf{A} = \mathbf{USV}^T \\
A \in \mathbb{R}^{m \times n}, U \in \mathbb{R}^{m \times m}, S \in \mathbb{R}^{m \times n}, V \in \mathbb{R}^{n \times n}
$$

Where $\mathbf{U}^T\mathbf{U} = \mathbf{I}$, $\mathbf{V}^T\mathbf{V} = \mathbf{I}$. 
- The columns of $\mathbf{U}$ are orthonormal eigenvectors of $\mathbf{AA}^T$
- The columns of $\mathbf{V}$ are orthonormal eigenvectors of $\mathbf{A}^T\mathbf{A}$
- $\mathbf{S}$ is a diagonal matrix containing the square roots of eigenvalues from $\mathbf{U}$ or $\mathbf{V}$ in descending order.

Full use of Numpy is allowed for this section (apart from the SVD method). You will have search around to identify which methods are required to be used/called.

In [5]:
## HELPER FUNCTION. DO NOT MODIFY THIS CELL
def reorder_eig_vectors(eig_tuple):
    eig_values, eig_vectors = eig_tuple
    idx = eig_values.argsort()[::-1]
    eig_values = eig_values[idx]
    eig_vectors = eig_vectors[:, idx]
    return eig_values, eig_vectors

In [56]:
A = np.array([[3,1,1],[-1,3,1]])

## Find U_ (i.e. calculate AA^T)
U_ = 

## Calculate the eigenvectors/eigenvalues of U_


## Use the helper function to reorder the eigens


[[11  1]
 [ 1 11]]
[12. 10.] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [61]:
## Find V_ (i.e. calculate A^TA)
V_ =

## Calculate the eigenvectors/eigenvalues of V_

## Use the helper function to reorder the eigens

## Transpose the V eigen vectors


In [57]:
## Initialise S as an m x n matrix of zeros
m = 
n = 
S = 


## Populate the diagonal of S with the square root of the non-zero eigenvalues from U and V.
## The diagonal should be filled in decending order (from largest to smallest) of these eigenvalues.


In [63]:
## Apply the SVD formula: A = USV.T
first_part =
reconstructed_A = 

# DON'T CHANGE THIS LINE. The final answer you obtain should be the same as the original A matrix.
reconstructed_A = -1 * reconstructed_A[[1,0]]
print(reconstructed_A)

[[ 3.  1.  1.]
 [-1.  3.  1.]]


## Calculus

Understanding the chain rule is essential to understanding how gradient based optimization, a technique will introduce later in the course, works. Here, we test two things:
- We ask you to work through an example of applying the chain rule
- We ask you to draw a tree-diagram for an algebraic derivative.

Please provide your answers by hand


Given that $z = f(x, y)$ where $x = g(t), y = h(t)$, the derivative of $z$ w.r.t. $t$ is given by:
<br>

$$
\frac{dz}{dt} = \frac{\partial f}{\partial x}\frac{dx}{dt} + \frac{\partial f}{\partial y}\frac{dy}{dt}
$$

1. <b>Let $z = xe^{xy}, x=t^2, y=t^{-1}$. Using the above formula, find $\frac{dz}{dt}$. You may leave your answer in terms of $x, y$ and $t$.</b>


Given that $z = f(x, y)$ where $x = g(s,t), \; y = h(s,t)$, the partial derivatives $\frac{\partial z}{\partial s}$ and $\frac{\partial z}{\partial t}$ are given by: 
<br>

$$
\\
\frac{\partial z}{\partial s} = \frac{\partial f}{\partial x}\frac{\partial x}{\partial s} + \frac{\partial f}{\partial y}\frac{\partial y}{\partial s} \\
\frac{\partial z}{\partial t} = \frac{\partial f}{\partial x}\frac{\partial x}{\partial t} + \frac{\partial f}{\partial y}\frac{\partial y}{\partial t}
$$

We can represent the partial derivatives in a tree-diagram as follows:

![partial_z](images\partial_z.png)

Similarly, if we are given $w = f(x,y,z),\; x=g_1(t),\; y=g_2(t),\; z=g_3(t)$, the tree-diagram, and derivative of $w$ w.r.t $t$ (i.e. $\frac{dw}{dt}$) is given by:

![partial_w](images\partial_w.png)
$$
\frac{dw}{dt} = \frac{\partial f}{\partial x}\frac{dx}{dt} + \frac{\partial f}{\partial y}\frac{dy}{dt} + \frac{\partial f}{\partial z}\frac{dz}{dt}
$$

2. <b>Draw the tree-diagram and find the partial derivative $\frac{\partial w}{\partial r}$ given $w = f(x,y,z),\; x=g_1(s,t,r),\; y=g_2(s,t,r),\; z=g_3(s,t,r)$</b>

## Probability

In machine learning, we tend to work with many random variables.

By hand (or in a document), **define and provide examples** of the following concepts:

1. Joint probability
2. Marginal probability
3. Conditional probability
4. Furthermore, using the chain rule of probability, rewrite the following equation in terms of conditional probabilities:
$$
p(x_1, x_2, x_3, x_4)
$$

The general chain rule is given by:
$$
p(x_1, ..., x_n) = \prod_i^n p(x_i | x_1, ..., x_{i-1}) 
$$